apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: baremetalassets.midas.io
spec:
  group: midas.io
  names:
    kind: BareMetalAsset
    listKind: BareMetalAssetList
    plural: baremetalassets
    singular: baremetalasset
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: BareMetalAsset is the Schema for the baremetalassets API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: BareMetalAssetSpec defines the desired state of BareMetalAsset
          properties:
            bmc:
              description: How do we connect to the BMC?
              properties:
                address:
                  description: Address holds the URL for accessing the controller
                    on the network.
                  type: string
                credentialsName:
                  description: The name of the secret containing the BMC credentials
                    (requires keys "username" and "password").
                  type: string
              required:
              - address
              - credentialsName
              type: object
            bootMACAddress:
              description: Which MAC address will PXE boot? This is optional for some
                types, but required for libvirt VMs driven by vbmc.
              pattern: '[0-9a-fA-F]{2}(:[0-9a-fA-F]{2}){5}'
              type: string
            hardwareProfile:
              description: What is the name of the hardware profile for this host?
                It should only be necessary to set this when inspection cannot automatically
                determine the profile.
              type: string
            role:
              description: Role holds the role of the asset
              enum:
              - master
              - worker
              type: string
          type: object
        status:
          description: BareMetalAssetStatus defines the observed state of BareMetalAsset
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
